apiVersion: v1
kind: Service
metadata:
  name: challenge-service
  labels:
    app: challenge
spec:
  type: NodePort
  selector:
    app: challenge
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000